const settings={coast:['SALT AIR & SOFT EVENING LIGHT','A little closer to the ocean.','Imagine a coastal celebration with an unhurried atmosphere, a sunset gathering and dinner beneath the stars.','We’ll discuss an indoor weather alternative, guest comfort, travel between locations and the right timing for your ceremony.'],city:['TIMELESS ELEGANCE & CITY LIGHTS','An occasion with a little grandeur.','Imagine a Colombo celebration: a beautifully dressed ballroom, a warm welcome and an evening that moves effortlessly from ceremony to dinner.','We’ll discuss venue access, guest arrivals, ceremony spaces, sound arrangements and a clear running order for the evening.'],hills:['GREEN VIEWS & A QUIETER RHYTHM','Let the landscape set the mood.','Imagine a hill-country or garden celebration with a sense of escape, intimate tables and time to linger with the people you love.','We’ll discuss travel time, accommodation, access for guests, temperature changes and a considered wet-weather plan.']};const tabs=[...document.querySelectorAll('[role=tab]')];function activate(tab){tabs.forEach(t=>{t.setAttribute('aria-selected',String(t===tab));t.tabIndex=t===tab?0:-1});const s=settings[tab.id];['setting-kicker','setting-title','setting-copy','setting-plan'].forEach((id,i)=>document.getElementById(id).textContent=s[i]);document.getElementById('setting').setAttribute('aria-labelledby',tab.id)}tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();activate(tabs[n]);tabs[n].focus()}})});document.querySelectorAll('.service-link').forEach(a=>{a.href='consultation.html?service='+encodeURIComponent(a.dataset.service)});

// Keep the homepage search aligned with the rolling years in the venue finder.
(() => {
 const year = document.querySelector('select[name="year"]');
 if (!year) return;
 const current = Number(new Intl.DateTimeFormat('en', {timeZone:'Asia/Colombo',year:'numeric'}).format(new Date()));
 year.innerHTML = Array.from({length:5}, (_,i) => `<option value="${current+i}">${current+i}</option>`).join('');
})();
