document.addEventListener('DOMContentLoaded',async()=>{
'use strict';
const data=await Serandib.directory(),engine=window.SerandibVenueEngine;
if(!data||!Array.isArray(data.venues)||!engine){const error=document.getElementById('filter-error');error.textContent='The venue directory could not load. Please refresh this page or contact Serandib for help.';error.hidden=false;return;}
const $=id=>document.getElementById(id),form=$('venue-filters');
const money=n=>'LKR '+Math.round(n).toLocaleString('en-US');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=null,result=null,selected=new Set(),timer;
const params=new URLSearchParams(location.search);for(const key of ['city','year','budget','guests','reserve'])if(params.has(key))$(key).value=params.get(key);if(params.has('date'))$('wedding-date').value=params.get('date');if(params.has('allowSpecialDays'))$('special-days').checked=params.get('allowSpecialDays')==='true';
const initialIds=(params.get('ids')||'').split(',').filter(Boolean);
$('wedding-date').min=engine.today();
$('city-options').innerHTML=['All Sri Lanka',...data.suggestedCities].map(city=>`<option value="${esc(city)}"></option>`).join('');
$('coverage-description').textContent=`${data.venues.length} hotels and venues across ${new Set(data.venues.map(v=>v.city)).size} cities and localities; ${data.venues.reduce((n,v)=>n+v.packages.length,0)} published package records, including reference prices awaiting year confirmation. This is a growing directory, not every hotel in Sri Lanka. A city suggestion does not mean we have verified venues there. Listings do not imply partnerships or available dates.`;
function read(){return{city:engine.canonicalCity(data,$('city').value),year:Number($('year').value),budget:Number($('budget').value),guests:Number($('guests').value),reserve:Number($('reserve').value),date:$('wedding-date').value,allowSpecialDays:$('special-days').checked};}
function source(item){return item.package.source||item.venue.source;}
function enquiry(items){const message=['Hello Chami & Levi, please help us confirm wedding venue prices and availability.',`City: ${current.city}`,`Wedding year: ${current.year}`,`Guests: ${current.guests}`,`Hotel / venue budget: ${money(current.budget)}`,`Wedding date: ${current.date||'Still deciding'}`,`Extra-cost allowance: ${money(current.reserve)}`,...items.map(item=>item.package?`${item.venue.name} — ${item.package.name}${item.subtotal!==null?': published subtotal '+money(item.subtotal):''}`:item.name),'Please confirm applicable taxes, venue fees, minimum attendance, inclusions and date availability.'].join('\n');return 'consultation.html';}
function rateLabel(p){return p.kind==='perPerson'?money(p.rate)+' / guest':'Published total for '+current.guests+' guests';}
function details(item){const p=item.package;const warnings=[...item.reasons,...(p.conditions||[])];if(item.needsDayConfirmation)warnings.unshift('Date must be confirmed as an eligible Sunday or Poya day.');if(!p.validUntil&&!p.priceYear)warnings.push('The source does not specify a rate expiry; confirm validity.');return `<details class="price-details"><summary>Price breakdown, inclusions & conditions</summary>${item.base!==null?`<dl><dt>${p.kind==='perPerson'?esc(money(p.rate)+' × '+current.guests+' guests'):'Published guest-tier total'}</dt><dd>${money(item.base)}</dd>${item.service?`<dt>Published service charge (${p.servicePercent}%)</dt><dd>${money(item.service)}</dd>`:''}${item.fixed?`<dt>${esc(p.fixedFeeLabel||'Published hall charge')}</dt><dd>${money(item.fixed)}</dd>`:''}<dt>Published subtotal</dt><dd>${money(item.subtotal)}</dd><dt>Your extra-cost allowance</dt><dd>${money(current.reserve)}</dd><dt>Planning amount before unconfirmed charges</dt><dd>${money(item.planningTotal)}</dd></dl>`:''}<p>${esc(p.taxNote||'Confirm all applicable charges with the hotel.')}</p><ul>${(p.includes||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul><ul>${warnings.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>${p.sourcePublishedLabel?esc(p.sourcePublishedLabel)+' · ':''}${p.validUntil?'Published rate valid until '+esc(p.validUntil):p.priceYear?'Brochure year: '+p.priceYear:'Validity not stated'} · Source checked ${esc(item.venue.checkedAt)}</p><a class="source-link" href="${esc(source(item))}" target="_blank" rel="noopener">Read the hotel’s original package source</a></details>`;}
function packageHTML(item,allowCompare){const p=item.package;const label=item.status==='potential'?'Potential fit · quote needed':item.status==='over'?'Above budget':'Quote needed';return `<div class="package-row"><div><h4>${esc(p.name)}</h4><p>${esc(rateLabel(p))}${p.servicePercent?' + '+p.servicePercent+'% service + taxes':''}</p>${details(item)}</div><div>${item.subtotal!==null?`<span class="price-label">${item.status==='quote'?'Reference subtotal · not a valid quote for your search':'Published subtotal, not final total'}</span><div class="price">${money(item.subtotal)}</div><p>${esc(p.taxNote)}</p>${current.reserve?`<p>With your allowance: <strong>${money(item.planningTotal)}</strong></p>`:''}${item.status==='quote'?'<p>'+esc(item.reasons.join(' '))+'</p>':'<p>'+(item.remaining>=0?money(item.remaining)+' left before unconfirmed costs':money(-item.remaining)+' above your budget')+'</p>'}`:`<div class="price">Quote required</div><p>${esc(item.reasons.join(' '))}</p>`}${item.needsDayConfirmation?'<p><strong>Sunday / Poya eligibility to confirm</strong></p>':''}</div><div class="package-actions"><span class="badge">${label}</span>${allowCompare?`<button class="outline-button compare-button" data-compare="${esc(item.id)}" type="button" aria-pressed="${selected.has(item.id)}">${selected.has(item.id)?'Remove from comparison':'Add to comparison'}</button>`:''}<a href="${esc(enquiry([item]))}" target="_blank" rel="noopener">Ask Serandib for a quote</a></div></div>`;}
function groups(items,allowCompare){const grouped=new Map();items.forEach(i=>{if(!grouped.has(i.venue.id))grouped.set(i.venue.id,[]);grouped.get(i.venue.id).push(i)});return [...grouped.values()].map(list=>{const v=list[0].venue;return `<article class="venue-card"><div class="venue-card-head"><div><span class="eyebrow">${esc(v.city)} · ${list.length} ${list.length===1?'package':'packages'}</span><h3><a href="venue.html?id=${encodeURIComponent(v.id)}">${esc(v.name)}</a></h3><p>${esc(v.description)}</p></div><div class="source-block"><a class="source-link" href="${esc(v.source)}" target="_blank" rel="noopener">Official hotel website</a><small>Checked ${esc(v.checkedAt)}</small></div></div>${list.map(i=>packageHTML(i,allowCompare)).join('')}</article>`}).join('');}
function render(){
 try{current=engine.validate(read());}catch(e){$('filter-error').textContent=e.message;$('filter-error').hidden=false;$('matching-results').innerHTML='';$('above-budget').hidden=true;$('quote-required').hidden=true;document.body.classList.remove('has-comparison');$('comparison').hidden=true;$('shortlist-dock').hidden=true;$('result-summary').textContent='Update your search details to see accurate estimates.';$('budget-summary').textContent='';$('year-coverage').textContent='';selected.clear();result=null;return;}
 $('filter-error').hidden=true;
 const previousIds=[...selected];
 result=engine.search(data,current);
 const facility=$('venue-facility').value;if(facility){for(const key of ['matching','over','unconfirmed'])result[key]=result[key].filter(i=>i.venue.facilities?.[facility]===true);result.quoteVenues=result.quoteVenues.filter(v=>v.facilities?.[facility]===true);}
 const setting=$('venue-setting').value;
 if(setting){const regex=setting==='indoor'?/ballroom|banquet|indoor|hall/i:/garden|lawn|outdoor|beach|ocean-facing/i;const fits=i=>regex.test(i.venue.description);result.matching=result.matching.filter(fits);result.over=result.over.filter(fits);result.unconfirmed=result.unconfirmed.filter(fits);result.quoteVenues=result.quoteVenues.filter(v=>regex.test(v.description));}
 document.querySelector('.sort-note').textContent=$('sort-order').value==='name'?'Hotels ordered A–Z':'Venues ranked by their lowest matching published subtotal';
 if($('sort-order').value==='name'){for(const key of ['matching','over','unconfirmed'])result[key].sort((a,b)=>a.venue.name.localeCompare(b.venue.name)||a.planningTotal-b.planningTotal);}
 const available=new Set(result.matching.map(i=>i.id));selected=new Set(previousIds.filter(id=>available.has(id)));const removed=previousIds.length-selected.size;
 $('comparison-status').textContent=removed?`${removed} selection(s) no longer match your search. Your remaining choices are kept.`:'Choose up to three packages to compare their prices and conditions.';
 $('results-title').textContent=current.city==='All Sri Lanka'?'Across Sri Lanka':'Possibilities in '+current.city;
 const dated=result.cityVenues.flatMap(v=>v.packages).filter(p=>!p.requiresYearConfirmation&&(p.priceYear===current.year||p.validUntil&&p.validUntil>=current.year+'-01-01'&&(!p.validFrom||p.validFrom<=current.year+'-12-31'))).length;
 $('year-coverage').textContent=dated?`${dated} package records have published validity covering at least part of ${current.year}. Confirm your exact date and all charges.`:`No package rates confirmed for ${current.year} in this part of the directory. Listed venues remain available for a quotation enquiry; this is not a statement about their availability.`;
 const venueCount=new Set(result.matching.map(i=>i.venue.id)).size;
 $('result-summary').textContent=`${result.matching.length} potential package ${result.matching.length===1?'match':'matches'} at ${venueCount} ${venueCount===1?'venue':'venues'} · ${result.cityVenues.length} listed venues for this location.`;
 $('budget-summary').innerHTML=`<span>Wedding year <strong>${current.year}</strong></span><span>Venue budget <strong>${money(current.budget)}</strong></span><span><strong>${current.guests}</strong> guests</span><span>Budget per guest <strong>${money(current.budget/current.guests)}</strong></span>${current.reserve?`<span>Extra-cost allowance <strong>${money(current.reserve)}</strong></span>`:''}${current.date?`<span>Date <strong>${esc(current.date)}</strong></span>`:''}`;
 $('matching-results').innerHTML=result.matching.length?groups(result.matching,true):`<div class="empty-state"><h3>${result.cityVenues.length?'Let’s explore another possibility.':'Our directory hasn’t reached '+esc(current.city)+' yet.'}</h3><p>${result.cityVenues.length?'No published package subtotal matches these filters. Review the quote-only options below, clear facility filters, adjust your guest count or budget, or ask us for a tailored search.':'This means we have no verified listings here yet—not that the city has no venues. We can help you explore it personally.'}</p><a class="button" href="${esc(enquiry([]))}" target="_blank" rel="noopener">Ask Serandib to help</a></div>`;
 if(!result.matching.length){const choices=[...new Set(data.venues.map(v=>v.city))].filter(city=>city!==current.city).slice(0,5);const alternative=document.createElement('div');alternative.className='notice';alternative.innerHTML='<p>Other listed locations to explore (outside your selected location):</p>'+choices.map(city=>{const params=new URLSearchParams({...current,city});return `<a class="text-link" style="display:inline-block;margin:0 20px 12px 0" href="venues.html?${esc(params.toString())}">${esc(city)}</a>`}).join('');$('matching-results').append(alternative);}
 $('above-title').textContent=`Above your budget (${result.over.length} packages)`;$('above-results').innerHTML=groups(result.over,false);$('above-budget').hidden=!result.over.length;
 $('quote-title').textContent=`Needs confirmation (${result.quoteVenues.length} venues, ${result.unconfirmed.length} additional packages)`;$('quote-results').innerHTML=groups(result.unconfirmed,false)+result.quoteVenues.map(v=>`<article class="quote-listing"><h3><a href="venue.html?id=${encodeURIComponent(v.id)}">${esc(v.name)}</a></h3><p>${esc(v.description)}</p><p>${esc(v.quoteReason)}${v.maxGuests&&current.guests>v.maxGuests?' Your guest count exceeds the published banquet capacity.':''}</p><div class="quote-actions"><a href="${esc(v.source)}" target="_blank" rel="noopener" class="source-link">Official hotel details</a><a href="${esc(enquiry([v]))}" target="_blank" rel="noopener" class="text-link">Request a quote</a></div><p class="small-note">Source checked ${esc(v.checkedAt)} · Not included in budget matches</p></article>`).join('');$('quote-required').hidden=!(result.quoteVenues.length||result.unconfirmed.length);$('quote-required').open=!result.matching.length;renderComparison();
}
function renderComparison(){
 const items=result?result.matching.filter(i=>selected.has(i.id)):[];document.body.classList.toggle('has-comparison',!!items.length);$('comparison').hidden=!items.length;$('shortlist-dock').hidden=!items.length;$('dock-count').textContent=`${items.length} of 3 packages selected`;
 document.querySelectorAll('[data-compare]').forEach(b=>{const checked=selected.has(b.dataset.compare);b.setAttribute('aria-pressed',String(checked));b.textContent=checked?'Remove from comparison':'Add to comparison';b.disabled=!checked&&selected.size>=3;});
 if(!items.length)return;
 const row=(name,fn)=>`<tr><th scope="row">${name}</th>${items.map(i=>`<td>${fn(i)}</td>`).join('')}</tr>`;
 $('comparison-table').innerHTML=`<table><caption class="sr-only">Published package comparison for ${current.guests} guests in ${esc(current.city)}</caption><thead><tr><th scope="col">Your priorities</th>${items.map(i=>`<th scope="col">${esc(i.venue.name)}<br>${esc(i.package.name)}<br><button class="outline-button" type="button" data-remove="${esc(i.id)}">Remove</button></th>`).join('')}</tr></thead><tbody>${row('Published price',i=>esc(rateLabel(i.package)))}${row('Published subtotal',i=>money(i.subtotal))}${row('With your allowance',i=>money(i.planningTotal))}${row('Budget remaining before unconfirmed costs',i=>money(i.remaining))}${row('Tax & extra charges',i=>esc(i.package.taxNote))}${row('Selected inclusions',i=>'<ul>'+i.package.includes.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>')}${row('Conditions',i=>esc([...(i.package.conditions||[]),i.needsDayConfirmation?'Sunday / Poya eligibility requires confirmation.':''].filter(Boolean).join(' ')))}${row('Rate validity',i=>esc(i.package.validUntil|| (i.package.priceYear?'Brochure year '+i.package.priceYear:'Not specified; confirm with hotel')))}${row('Official source',i=>`<a class="source-link" href="${esc(source(i))}" target="_blank" rel="noopener">View source</a><br>Checked ${esc(i.venue.checkedAt)}`)}</tbody></table>`;
 $('shortlist-enquiry').href=enquiry(items);
}
form.addEventListener('submit',e=>{e.preventDefault();clearTimeout(timer);render();if(result)Serandib.event('venue_search')});form.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(render,250)});form.addEventListener('change',()=>{clearTimeout(timer);render()});
$('matching-results').addEventListener('click',e=>{const button=e.target.closest('[data-compare]');if(!button)return;const id=button.dataset.compare;if(selected.has(id))selected.delete(id);else if(selected.size<3)selected.add(id);renderComparison();$('comparison-status').textContent=`${selected.size} of 3 packages selected. Comparison table is below the matching venues.`;});
$('comparison-table').addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(!button)return;const id=button.dataset.remove;selected.delete(id);renderComparison();const original=document.querySelector(`[data-compare="${id}"]`);if(original)original.focus();$('comparison-status').textContent=`${selected.size} of 3 packages selected.`;});
$('clear-comparison').addEventListener('click',()=>{selected.clear();renderComparison();$('comparison-status').textContent='Comparison cleared.';document.querySelector('[data-compare]')?.focus()});
$('save-shortlist').textContent='Preview only';$('save-shortlist').addEventListener('click',async()=>{if(window.SERANDIB_PREVIEW){$('save-status').textContent='Online saving is available only on the full hosted platform.';return;}const button=$('save-shortlist');button.disabled=true;$('save-status').textContent='Saving your shortlist…';try{await Serandib.session;const saved=await Serandib.request('/api/shortlists',{method:'POST',body:JSON.stringify({settings:current,ids:[...selected]})});$('save-status').innerHTML=`Saved. <a class="text-link" href="${esc(saved.url)}">Open and share your shortlist</a>`;Serandib.event('shortlist_saved')}catch(e){$('save-status').textContent=e.message}finally{button.disabled=false}});
render();initialIds.filter(id=>result?.matching.some(i=>i.id===id)).slice(0,3).forEach(id=>selected.add(id));renderComparison();
});
